### PR TITLE
fix: fix edcVersion and postgres dependency for azure launcher

### PR DESCRIPTION
**Pull request by robertschubert**
## What this PR changes/adds

- Fix edcVersion in gradle.properties
- added postgres dependency into azure launcher

## Checklist

- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] documented code?
- [ ] assigned appropriate label?
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Samples/blob/main/CONTRIBUTING.md#submit-a-pull-request) for details_)

### CODE REVIEW

**Comment by robertschubert** [comment]
@JulianLegler 
**Please no merge yet**. Still haven't found the correct configuration for the database so i rolled back the (dependency) changes temporarily.
Current error:
`2024-11-15 16:40:18 SEVERE : Error booting runtime: begin 24, end 23, length 23`
Did you also experience that?

Moreover I had to specify the config `edc.datasource.password.url` which I cannot find in your config. I will need to have a closer look next week.

**Comment by JulianLegler** [comment]
Sorry the error doesn't seem familiar to me. But it's already a little bit ago as I looked into this. I can only point you to the docker-compose-dev.yaml. It should result in a local setup with a working database. Would have hoped that it would be similar for your azure setup.

**Comment by robertschubert** [comment]
> Sorry the error doesn't seem familiar to me. But it's already a little bit ago as I looked into this. I can only point you to the docker-compose-dev.yaml. It should result in a local setup with a working database. Would have hoped that it would be similar for your azure setup.

ready to merge now.
After renaming variables from `EDC_DATASOURCE_USERNAME` to `EDC_DATASOURCE_DEFAULT_USER` and `EDC_DATASOURCE_PASSWORD` to `EDC_DATASOURCE_DEFAULT_PASSWORD` everything went fine.
@JulianLegler  With this approach you can leave the `?user=connector&password=password` part out of all URLs.

**Review by JulianLegler — APPROVED** [review]
Will trust you that it works as I cant test the azure related stuff myself

**Comment by robertschubert** [comment]
already successfully tested it in our azure k8s cluster.
will merge now.

**Pull request merged**
